### ISSUE TITLE
設定画面にアクセスできない

### ISSUE THREAD

**Issue by cyatarow** [mkizka/MTDeck#6]
このスクリプトを導入すると、tweetdeckの設定画面にアクセスできなくなります。

**Comment by mkizka** [comment]
画面の左あたりを右にスワイプすると設定ボタンを含むメニューが出ると思うんですが、それが出来ないということでしょうか？

以下は古いバージョンの動画デモですがこれの0:03みたいな感じです
https://streamable.com/oocea

**Comment by cyatarow** [comment]
> 画面の左あたりを右にスワイプすると

出てきました。ありがとうございます。
