### ISSUE TITLE
右下のツイートボタンが常に表示されるせいで、ツイートの会話の文章と重なっている

### ISSUE THREAD

**Issue by cyatarow** [mkizka/MTDeck#7]
例: 僕のツイートより
![Screenshot_20201016-221602](https://user-images.githubusercontent.com/26016252/96262964-6aed2100-0ffd-11eb-87ab-6529a992b83c.png)

右下のツイートボタンが、文章と重なって表示されており、文章が見えにくくなっています。
ツイートの詳細画面では、非表示にできるように為りませんか？

**Comment by mkizka** [comment]
こちら確かにそうだと思ったので https://github.com/mkizka/MTDeck/commit/d66d8a62e2e9495028abba02ce17ae6745e45b5b で対応しました。この変更を含む`v1.6.7`は現在審査中です
ありがとうございました！

**Comment by cyatarow** [comment]
[スクリプト本体](https://github.com/mkizka/MTDeck/raw/master/dist/mtdeck.user.js)を直接実行できる環境なので、修正を確認できました。ありがとうございます。

しかし、今度は、ツイート詳細画面から前の画面に戻ると、カラムを切り替えるまで非表示になりっぱなしになっています。
前の画面に戻った時点で、再表示できるようになりませんか?

**Comment by mkizka** [comment]
おそらく同じと思われるものを確認済みでIssue建ててます(#9)
今日はもう作業出来ないので明日治しておきます

**Comment by mkizka** [comment]
https://github.com/mkizka/MTDeck/commit/d9c241de8f112f8322b65927ddf4442189401a2c で治しました！
