### ISSUE TITLE
画像サムネイル非表示設定と、センシティブ画像非表示設定の、組み合わせの不具合

### ISSUE THREAD

**Issue by cyatarow** [mkizka/MTDeck#8]
MTDeck側の「ツイートの画像サムネイルを非表示」設定をONにして、
TweetDeck側の「Display media that may contain sensitive content」（センシティブな画像でもサムネイルを見せる）設定をOFFにすると、
設定同士が競合しているのか、センシティブ画像の警告ウィンドウが、他のツイートにまたがって表示されています。
![Screenshot_20201016-223151_1](https://user-images.githubusercontent.com/26016252/96265434-6413dd80-1000-11eb-9dbc-0237ade7be9e.png)

**Comment by mkizka** [comment]
センシティブ設定は普段許可にしていたため気付きませんでした！報告ありがとうございます
いつになるかは分かりませんが気が向いたら対応しておきます

**Comment by mkizka** [comment]
こちら https://github.com/mkizka/MTDeck/commit/72e545cf7c7f793226813073e8a1b4526aba2c74 で対応しました！
